"""
India Districts, State Crop Mappings, and Hindi State Translations.

Pure Python data file containing:
- DISTRICTS: List of tuples (district_name, state_name) covering all 28 states and 8 union territories (~786 districts).
- STATE_CROPS: Dict mapping each state/UT to its top 2-3 crops where power weeders are commonly used.
- HINDI_STATES: Dict mapping each state/UT name to its Hindi translation in Devanagari script.
"""

DISTRICTS = [
    # =========================================================================
    # 1. Andhra Pradesh (26 districts)
    # =========================================================================
    ("Alluri Sitharama Raju", "Andhra Pradesh"),
    ("Anakapalli", "Andhra Pradesh"),
    ("Anantapur", "Andhra Pradesh"),
    ("Annamayya", "Andhra Pradesh"),
    ("Bapatla", "Andhra Pradesh"),
    ("Chittoor", "Andhra Pradesh"),
    ("Dr. B.R. Ambedkar Konaseema", "Andhra Pradesh"),
    ("East Godavari", "Andhra Pradesh"),
    ("Eluru", "Andhra Pradesh"),
    ("Guntur", "Andhra Pradesh"),
    ("Kadapa", "Andhra Pradesh"),
    ("Kakinada", "Andhra Pradesh"),
    ("Konaseema", "Andhra Pradesh"),
    ("Krishna", "Andhra Pradesh"),
    ("Kurnool", "Andhra Pradesh"),
    ("Nandyal", "Andhra Pradesh"),
    ("NTR", "Andhra Pradesh"),
    ("Palnadu", "Andhra Pradesh"),
    ("Parvathipuram Manyam", "Andhra Pradesh"),
    ("Prakasam", "Andhra Pradesh"),
    ("Nellore", "Andhra Pradesh"),
    ("Sri Sathya Sai", "Andhra Pradesh"),
    ("Srikakulam", "Andhra Pradesh"),
    ("Tirupati", "Andhra Pradesh"),
    ("Visakhapatnam", "Andhra Pradesh"),
    ("Vizianagaram", "Andhra Pradesh"),
    ("West Godavari", "Andhra Pradesh"),

    # =========================================================================
    # 2. Arunachal Pradesh (26 districts)
    # =========================================================================
    ("Anjaw", "Arunachal Pradesh"),
    ("Changlang", "Arunachal Pradesh"),
    ("Dibang Valley", "Arunachal Pradesh"),
    ("East Kameng", "Arunachal Pradesh"),
    ("East Siang", "Arunachal Pradesh"),
    ("Itanagar Capital Complex", "Arunachal Pradesh"),
    ("Kamle", "Arunachal Pradesh"),
    ("Kra Daadi", "Arunachal Pradesh"),
    ("Kurung Kumey", "Arunachal Pradesh"),
    ("Lepa Rada", "Arunachal Pradesh"),
    ("Lohit", "Arunachal Pradesh"),
    ("Longding", "Arunachal Pradesh"),
    ("Lower Dibang Valley", "Arunachal Pradesh"),
    ("Lower Siang", "Arunachal Pradesh"),
    ("Lower Subansiri", "Arunachal Pradesh"),
    ("Namsai", "Arunachal Pradesh"),
    ("Pakke Kessang", "Arunachal Pradesh"),
    ("Papum Pare", "Arunachal Pradesh"),
    ("Shi Yomi", "Arunachal Pradesh"),
    ("Siang", "Arunachal Pradesh"),
    ("Tawang", "Arunachal Pradesh"),
    ("Tirap", "Arunachal Pradesh"),
    ("Upper Siang", "Arunachal Pradesh"),
    ("Upper Subansiri", "Arunachal Pradesh"),
    ("West Kameng", "Arunachal Pradesh"),
    ("West Siang", "Arunachal Pradesh"),

    # =========================================================================
    # 3. Assam (35 districts)
    # =========================================================================
    ("Bajali", "Assam"),
    ("Baksa", "Assam"),
    ("Barpeta", "Assam"),
    ("Biswanath", "Assam"),
    ("Bongaigaon", "Assam"),
    ("Cachar", "Assam"),
    ("Charaideo", "Assam"),
    ("Chirang", "Assam"),
    ("Darrang", "Assam"),
    ("Dhemaji", "Assam"),
    ("Dhubri", "Assam"),
    ("Dibrugarh", "Assam"),
    ("Dima Hasao", "Assam"),
    ("Goalpara", "Assam"),
    ("Golaghat", "Assam"),
    ("Hailakandi", "Assam"),
    ("Hojai", "Assam"),
    ("Jorhat", "Assam"),
    ("Kamrup", "Assam"),
    ("Kamrup Metropolitan", "Assam"),
    ("Karbi Anglong", "Assam"),
    ("Karimganj", "Assam"),
    ("Kokrajhar", "Assam"),
    ("Lakhimpur", "Assam"),
    ("Majuli", "Assam"),
    ("Morigaon", "Assam"),
    ("Nagaon", "Assam"),
    ("Nalbari", "Assam"),
    ("Sivasagar", "Assam"),
    ("Sonitpur", "Assam"),
    ("South Salmara-Mankachar", "Assam"),
    ("Tamulpur", "Assam"),
    ("Tinsukia", "Assam"),
    ("Udalguri", "Assam"),
    ("West Karbi Anglong", "Assam"),

    # =========================================================================
    # 4. Bihar (38 districts)
    # =========================================================================
    ("Araria", "Bihar"),
    ("Arwal", "Bihar"),
    ("Aurangabad", "Bihar"),
    ("Banka", "Bihar"),
    ("Begusarai", "Bihar"),
    ("Bhagalpur", "Bihar"),
    ("Bhojpur", "Bihar"),
    ("Buxar", "Bihar"),
    ("Darbhanga", "Bihar"),
    ("East Champaran", "Bihar"),
    ("Gaya", "Bihar"),
    ("Gopalganj", "Bihar"),
    ("Jamui", "Bihar"),
    ("Jehanabad", "Bihar"),
    ("Kaimur", "Bihar"),
    ("Katihar", "Bihar"),
    ("Khagaria", "Bihar"),
    ("Kishanganj", "Bihar"),
    ("Lakhisarai", "Bihar"),
    ("Madhepura", "Bihar"),
    ("Madhubani", "Bihar"),
    ("Munger", "Bihar"),
    ("Muzaffarpur", "Bihar"),
    ("Nalanda", "Bihar"),
    ("Nawada", "Bihar"),
    ("Patna", "Bihar"),
    ("Purnia", "Bihar"),
    ("Rohtas", "Bihar"),
    ("Saharsa", "Bihar"),
    ("Samastipur", "Bihar"),
    ("Saran", "Bihar"),
    ("Sheikhpura", "Bihar"),
    ("Sheohar", "Bihar"),
    ("Sitamarhi", "Bihar"),
    ("Siwan", "Bihar"),
    ("Supaul", "Bihar"),
    ("Vaishali", "Bihar"),
    ("West Champaran", "Bihar"),

    # =========================================================================
    # 5. Chhattisgarh (33 districts)
    # =========================================================================
    ("Balod", "Chhattisgarh"),
    ("Baloda Bazar-Bhatapara", "Chhattisgarh"),
    ("Balrampur-Ramanujganj", "Chhattisgarh"),
    ("Bastar", "Chhattisgarh"),
    ("Bemetara", "Chhattisgarh"),
    ("Bijapur", "Chhattisgarh"),
    ("Bilaspur", "Chhattisgarh"),
    ("Dantewada", "Chhattisgarh"),
    ("Dhamtari", "Chhattisgarh"),
    ("Durg", "Chhattisgarh"),
    ("Gariaband", "Chhattisgarh"),
    ("Gaurela-Pendra-Marwahi", "Chhattisgarh"),
    ("Janjgir-Champa", "Chhattisgarh"),
    ("Jashpur", "Chhattisgarh"),
    ("Kabirdham", "Chhattisgarh"),
    ("Kanker", "Chhattisgarh"),
    ("Khairagarh-Chhuikhadan-Gandai", "Chhattisgarh"),
    ("Kondagaon", "Chhattisgarh"),
    ("Korba", "Chhattisgarh"),
    ("Koriya", "Chhattisgarh"),
    ("Mahasamund", "Chhattisgarh"),
    ("Manendragarh-Chirmiri-Bharatpur", "Chhattisgarh"),
    ("Mohla-Manpur-Ambagarh Chowki", "Chhattisgarh"),
    ("Mungeli", "Chhattisgarh"),
    ("Narayanpur", "Chhattisgarh"),
    ("Raigarh", "Chhattisgarh"),
    ("Raipur", "Chhattisgarh"),
    ("Rajnandgaon", "Chhattisgarh"),
    ("Sakti", "Chhattisgarh"),
    ("Sarangarh-Bilaigarh", "Chhattisgarh"),
    ("Sukma", "Chhattisgarh"),
    ("Surajpur", "Chhattisgarh"),
    ("Surguja", "Chhattisgarh"),

    # =========================================================================
    # 6. Goa (2 districts)
    # =========================================================================
    ("North Goa", "Goa"),
    ("South Goa", "Goa"),

    # =========================================================================
    # 7. Gujarat (33 districts)
    # =========================================================================
    ("Ahmedabad", "Gujarat"),
    ("Amreli", "Gujarat"),
    ("Anand", "Gujarat"),
    ("Aravalli", "Gujarat"),
    ("Banaskantha", "Gujarat"),
    ("Bharuch", "Gujarat"),
    ("Bhavnagar", "Gujarat"),
    ("Botad", "Gujarat"),
    ("Chhota Udaipur", "Gujarat"),
    ("Dahod", "Gujarat"),
    ("Dang", "Gujarat"),
    ("Devbhumi Dwarka", "Gujarat"),
    ("Gandhinagar", "Gujarat"),
    ("Gir Somnath", "Gujarat"),
    ("Jamnagar", "Gujarat"),
    ("Junagadh", "Gujarat"),
    ("Kheda", "Gujarat"),
    ("Kutch", "Gujarat"),
    ("Mahisagar", "Gujarat"),
    ("Mehsana", "Gujarat"),
    ("Morbi", "Gujarat"),
    ("Narmada", "Gujarat"),
    ("Navsari", "Gujarat"),
    ("Panchmahal", "Gujarat"),
    ("Patan", "Gujarat"),
    ("Porbandar", "Gujarat"),
    ("Rajkot", "Gujarat"),
    ("Sabarkantha", "Gujarat"),
    ("Surat", "Gujarat"),
    ("Surendranagar", "Gujarat"),
    ("Tapi", "Gujarat"),
    ("Vadodara", "Gujarat"),
    ("Valsad", "Gujarat"),

    # =========================================================================
    # 8. Haryana (22 districts)
    # =========================================================================
    ("Ambala", "Haryana"),
    ("Bhiwani", "Haryana"),
    ("Charkhi Dadri", "Haryana"),
    ("Faridabad", "Haryana"),
    ("Fatehabad", "Haryana"),
    ("Gurugram", "Haryana"),
    ("Hisar", "Haryana"),
    ("Jhajjar", "Haryana"),
    ("Jind", "Haryana"),
    ("Kaithal", "Haryana"),
    ("Karnal", "Haryana"),
    ("Kurukshetra", "Haryana"),
    ("Mahendragarh", "Haryana"),
    ("Nuh", "Haryana"),
    ("Palwal", "Haryana"),
    ("Panchkula", "Haryana"),
    ("Panipat", "Haryana"),
    ("Rewari", "Haryana"),
    ("Rohtak", "Haryana"),
    ("Sirsa", "Haryana"),
    ("Sonipat", "Haryana"),
    ("Yamunanagar", "Haryana"),

    # =========================================================================
    # 9. Himachal Pradesh (12 districts)
    # =========================================================================
    ("Bilaspur", "Himachal Pradesh"),
    ("Chamba", "Himachal Pradesh"),
    ("Hamirpur", "Himachal Pradesh"),
    ("Kangra", "Himachal Pradesh"),
    ("Kinnaur", "Himachal Pradesh"),
    ("Kullu", "Himachal Pradesh"),
    ("Lahaul and Spiti", "Himachal Pradesh"),
    ("Mandi", "Himachal Pradesh"),
    ("Shimla", "Himachal Pradesh"),
    ("Sirmaur", "Himachal Pradesh"),
    ("Solan", "Himachal Pradesh"),
    ("Una", "Himachal Pradesh"),

    # =========================================================================
    # 10. Jharkhand (24 districts)
    # =========================================================================
    ("Bokaro", "Jharkhand"),
    ("Chatra", "Jharkhand"),
    ("Deoghar", "Jharkhand"),
    ("Dhanbad", "Jharkhand"),
    ("Dumka", "Jharkhand"),
    ("East Singhbhum", "Jharkhand"),
    ("Garhwa", "Jharkhand"),
    ("Giridih", "Jharkhand"),
    ("Godda", "Jharkhand"),
    ("Gumla", "Jharkhand"),
    ("Hazaribagh", "Jharkhand"),
    ("Jamtara", "Jharkhand"),
    ("Khunti", "Jharkhand"),
    ("Koderma", "Jharkhand"),
    ("Latehar", "Jharkhand"),
    ("Lohardaga", "Jharkhand"),
    ("Pakur", "Jharkhand"),
    ("Palamu", "Jharkhand"),
    ("Ramgarh", "Jharkhand"),
    ("Ranchi", "Jharkhand"),
    ("Sahibganj", "Jharkhand"),
    ("Saraikela Kharsawan", "Jharkhand"),
    ("Simdega", "Jharkhand"),
    ("West Singhbhum", "Jharkhand"),

    # =========================================================================
    # 11. Karnataka (31 districts)
    # =========================================================================
    ("Bagalkote", "Karnataka"),
    ("Ballari", "Karnataka"),
    ("Belagavi", "Karnataka"),
    ("Bengaluru Rural", "Karnataka"),
    ("Bengaluru Urban", "Karnataka"),
    ("Bidar", "Karnataka"),
    ("Chamarajanagar", "Karnataka"),
    ("Chikkaballapura", "Karnataka"),
    ("Chikkamagaluru", "Karnataka"),
    ("Chitradurga", "Karnataka"),
    ("Dakshina Kannada", "Karnataka"),
    ("Davanagere", "Karnataka"),
    ("Dharwad", "Karnataka"),
    ("Gadag", "Karnataka"),
    ("Hassan", "Karnataka"),
    ("Haveri", "Karnataka"),
    ("Kalaburagi", "Karnataka"),
    ("Kodagu", "Karnataka"),
    ("Kolar", "Karnataka"),
    ("Koppal", "Karnataka"),
    ("Mandya", "Karnataka"),
    ("Mysuru", "Karnataka"),
    ("Raichur", "Karnataka"),
    ("Ramanagara", "Karnataka"),
    ("Shivamogga", "Karnataka"),
    ("Tumakuru", "Karnataka"),
    ("Udupi", "Karnataka"),
    ("Uttara Kannada", "Karnataka"),
    ("Vijayanagara", "Karnataka"),
    ("Vijayapura", "Karnataka"),
    ("Yadgir", "Karnataka"),

    # =========================================================================
    # 12. Kerala (14 districts)
    # =========================================================================
    ("Alappuzha", "Kerala"),
    ("Ernakulam", "Kerala"),
    ("Idukki", "Kerala"),
    ("Kannur", "Kerala"),
    ("Kasaragod", "Kerala"),
    ("Kollam", "Kerala"),
    ("Kottayam", "Kerala"),
    ("Kozhikode", "Kerala"),
    ("Malappuram", "Kerala"),
    ("Palakkad", "Kerala"),
    ("Pathanamthitta", "Kerala"),
    ("Thiruvananthapuram", "Kerala"),
    ("Thrissur", "Kerala"),
    ("Wayanad", "Kerala"),

    # =========================================================================
    # 13. Madhya Pradesh (55 districts)
    # =========================================================================
    ("Agar Malwa", "Madhya Pradesh"),
    ("Alirajpur", "Madhya Pradesh"),
    ("Anuppur", "Madhya Pradesh"),
    ("Ashoknagar", "Madhya Pradesh"),
    ("Balaghat", "Madhya Pradesh"),
    ("Barwani", "Madhya Pradesh"),
    ("Betul", "Madhya Pradesh"),
    ("Bhind", "Madhya Pradesh"),
    ("Bhopal", "Madhya Pradesh"),
    ("Burhanpur", "Madhya Pradesh"),
    ("Chhatarpur", "Madhya Pradesh"),
    ("Chhindwara", "Madhya Pradesh"),
    ("Damoh", "Madhya Pradesh"),
    ("Datia", "Madhya Pradesh"),
    ("Dewas", "Madhya Pradesh"),
    ("Dhar", "Madhya Pradesh"),
    ("Dindori", "Madhya Pradesh"),
    ("Guna", "Madhya Pradesh"),
    ("Gwalior", "Madhya Pradesh"),
    ("Harda", "Madhya Pradesh"),
    ("Indore", "Madhya Pradesh"),
    ("Jabalpur", "Madhya Pradesh"),
    ("Jhabua", "Madhya Pradesh"),
    ("Katni", "Madhya Pradesh"),
    ("Khandwa", "Madhya Pradesh"),
    ("Khargone", "Madhya Pradesh"),
    ("Maihar", "Madhya Pradesh"),
    ("Mandla", "Madhya Pradesh"),
    ("Mandsaur", "Madhya Pradesh"),
    ("Mauganj", "Madhya Pradesh"),
    ("Morena", "Madhya Pradesh"),
    ("Narmadapuram", "Madhya Pradesh"),
    ("Narsinghpur", "Madhya Pradesh"),
    ("Neemuch", "Madhya Pradesh"),
    ("Niwari", "Madhya Pradesh"),
    ("Pandhurna", "Madhya Pradesh"),
    ("Panna", "Madhya Pradesh"),
    ("Raisen", "Madhya Pradesh"),
    ("Rajgarh", "Madhya Pradesh"),
    ("Ratlam", "Madhya Pradesh"),
    ("Rewa", "Madhya Pradesh"),
    ("Sagar", "Madhya Pradesh"),
    ("Satna", "Madhya Pradesh"),
    ("Sehore", "Madhya Pradesh"),
    ("Seoni", "Madhya Pradesh"),
    ("Shahdol", "Madhya Pradesh"),
    ("Shajapur", "Madhya Pradesh"),
    ("Sheopur", "Madhya Pradesh"),
    ("Shivpuri", "Madhya Pradesh"),
    ("Sidhi", "Madhya Pradesh"),
    ("Singrauli", "Madhya Pradesh"),
    ("Tikamgarh", "Madhya Pradesh"),
    ("Ujjain", "Madhya Pradesh"),
    ("Umaria", "Madhya Pradesh"),
    ("Vidisha", "Madhya Pradesh"),

    # =========================================================================
    # 14. Maharashtra (36 districts)
    # =========================================================================
    ("Ahmednagar", "Maharashtra"),
    ("Akola", "Maharashtra"),
    ("Amravati", "Maharashtra"),
    ("Aurangabad", "Maharashtra"),
    ("Beed", "Maharashtra"),
    ("Bhandara", "Maharashtra"),
    ("Buldhana", "Maharashtra"),
    ("Chandrapur", "Maharashtra"),
    ("Dhule", "Maharashtra"),
    ("Gadchiroli", "Maharashtra"),
    ("Gondia", "Maharashtra"),
    ("Hingoli", "Maharashtra"),
    ("Jalgaon", "Maharashtra"),
    ("Jalna", "Maharashtra"),
    ("Kolhapur", "Maharashtra"),
    ("Latur", "Maharashtra"),
    ("Mumbai City", "Maharashtra"),
    ("Mumbai Suburban", "Maharashtra"),
    ("Nagpur", "Maharashtra"),
    ("Nanded", "Maharashtra"),
    ("Nandurbar", "Maharashtra"),
    ("Nashik", "Maharashtra"),
    ("Osmanabad", "Maharashtra"),
    ("Palghar", "Maharashtra"),
    ("Parbhani", "Maharashtra"),
    ("Pune", "Maharashtra"),
    ("Raigad", "Maharashtra"),
    ("Ratnagiri", "Maharashtra"),
    ("Sangli", "Maharashtra"),
    ("Satara", "Maharashtra"),
    ("Sindhudurg", "Maharashtra"),
    ("Solapur", "Maharashtra"),
    ("Thane", "Maharashtra"),
    ("Wardha", "Maharashtra"),
    ("Washim", "Maharashtra"),
    ("Yavatmal", "Maharashtra"),

    # =========================================================================
    # 15. Manipur (16 districts)
    # =========================================================================
    ("Bishnupur", "Manipur"),
    ("Chandel", "Manipur"),
    ("Churachandpur", "Manipur"),
    ("Imphal East", "Manipur"),
    ("Imphal West", "Manipur"),
    ("Jiribam", "Manipur"),
    ("Kakching", "Manipur"),
    ("Kamjong", "Manipur"),
    ("Kangpokpi", "Manipur"),
    ("Noney", "Manipur"),
    ("Pherzawl", "Manipur"),
    ("Senapati", "Manipur"),
    ("Tamenglong", "Manipur"),
    ("Tengnoupal", "Manipur"),
    ("Thoubal", "Manipur"),
    ("Ukhrul", "Manipur"),

    # =========================================================================
    # 16. Meghalaya (12 districts)
    # =========================================================================
    ("East Garo Hills", "Meghalaya"),
    ("East Jaintia Hills", "Meghalaya"),
    ("East Khasi Hills", "Meghalaya"),
    ("Eastern West Khasi Hills", "Meghalaya"),
    ("North Garo Hills", "Meghalaya"),
    ("Ri Bhoi", "Meghalaya"),
    ("South Garo Hills", "Meghalaya"),
    ("South West Garo Hills", "Meghalaya"),
    ("South West Khasi Hills", "Meghalaya"),
    ("West Garo Hills", "Meghalaya"),
    ("West Jaintia Hills", "Meghalaya"),
    ("West Khasi Hills", "Meghalaya"),

    # =========================================================================
    # 17. Mizoram (11 districts)
    # =========================================================================
    ("Aizawl", "Mizoram"),
    ("Champhai", "Mizoram"),
    ("Hnahthial", "Mizoram"),
    ("Khawzawl", "Mizoram"),
    ("Kolasib", "Mizoram"),
    ("Lawngtlai", "Mizoram"),
    ("Lunglei", "Mizoram"),
    ("Mamit", "Mizoram"),
    ("Saitual", "Mizoram"),
    ("Serchhip", "Mizoram"),
    ("Siaha", "Mizoram"),

    # =========================================================================
    # 18. Nagaland (16 districts)
    # =========================================================================
    ("Chümoukedima", "Nagaland"),
    ("Dimapur", "Nagaland"),
    ("Kiphire", "Nagaland"),
    ("Kohima", "Nagaland"),
    ("Longleng", "Nagaland"),
    ("Mokokchung", "Nagaland"),
    ("Mon", "Nagaland"),
    ("Niuland", "Nagaland"),
    ("Noklak", "Nagaland"),
    ("Peren", "Nagaland"),
    ("Phek", "Nagaland"),
    ("Shamator", "Nagaland"),
    ("Tseminyu", "Nagaland"),
    ("Tuensang", "Nagaland"),
    ("Wokha", "Nagaland"),
    ("Zunheboto", "Nagaland"),

    # =========================================================================
    # 19. Odisha (30 districts)
    # =========================================================================
    ("Angul", "Odisha"),
    ("Balangir", "Odisha"),
    ("Balasore", "Odisha"),
    ("Bargarh", "Odisha"),
    ("Bhadrak", "Odisha"),
    ("Boudh", "Odisha"),
    ("Cuttack", "Odisha"),
    ("Deogarh", "Odisha"),
    ("Dhenkanal", "Odisha"),
    ("Gajapati", "Odisha"),
    ("Ganjam", "Odisha"),
    ("Jagatsinghpur", "Odisha"),
    ("Jajpur", "Odisha"),
    ("Jharsuguda", "Odisha"),
    ("Kalahandi", "Odisha"),
    ("Kandhamal", "Odisha"),
    ("Kendrapara", "Odisha"),
    ("Kendujhar", "Odisha"),
    ("Khordha", "Odisha"),
    ("Koraput", "Odisha"),
    ("Malkangiri", "Odisha"),
    ("Mayurbhanj", "Odisha"),
    ("Nabarangpur", "Odisha"),
    ("Nayagarh", "Odisha"),
    ("Nuapada", "Odisha"),
    ("Puri", "Odisha"),
    ("Rayagada", "Odisha"),
    ("Sambalpur", "Odisha"),
    ("Subarnapur", "Odisha"),
    ("Sundargarh", "Odisha"),

    # =========================================================================
    # 20. Punjab (23 districts)
    # =========================================================================
    ("Amritsar", "Punjab"),
    ("Barnala", "Punjab"),
    ("Bathinda", "Punjab"),
    ("Faridkot", "Punjab"),
    ("Fatehgarh Sahib", "Punjab"),
    ("Fazilka", "Punjab"),
    ("Ferozepur", "Punjab"),
    ("Gurdaspur", "Punjab"),
    ("Hoshiarpur", "Punjab"),
    ("Jalandhar", "Punjab"),
    ("Kapurthala", "Punjab"),
    ("Ludhiana", "Punjab"),
    ("Malerkotla", "Punjab"),
    ("Mansa", "Punjab"),
    ("Moga", "Punjab"),
    ("Muktsar", "Punjab"),
    ("Pathankot", "Punjab"),
    ("Patiala", "Punjab"),
    ("Rupnagar", "Punjab"),
    ("Sahibzada Ajit Singh Nagar", "Punjab"),
    ("Sangrur", "Punjab"),
    ("Shahid Bhagat Singh Nagar", "Punjab"),
    ("Tarn Taran", "Punjab"),

    # =========================================================================
    # 21. Rajasthan (50 districts)
    # =========================================================================
    ("Ajmer", "Rajasthan"),
    ("Alwar", "Rajasthan"),
    ("Anupgarh", "Rajasthan"),
    ("Balotra", "Rajasthan"),
    ("Banswara", "Rajasthan"),
    ("Baran", "Rajasthan"),
    ("Barmer", "Rajasthan"),
    ("Beawar", "Rajasthan"),
    ("Bharatpur", "Rajasthan"),
    ("Bhilwara", "Rajasthan"),
    ("Bikaner", "Rajasthan"),
    ("Bundi", "Rajasthan"),
    ("Chittorgarh", "Rajasthan"),
    ("Churu", "Rajasthan"),
    ("Dausa", "Rajasthan"),
    ("Deeg", "Rajasthan"),
    ("Dholpur", "Rajasthan"),
    ("Didwana-Kuchaman", "Rajasthan"),
    ("Dudu", "Rajasthan"),
    ("Dungarpur", "Rajasthan"),
    ("Gangapur City", "Rajasthan"),
    ("Hanumangarh", "Rajasthan"),
    ("Jaipur", "Rajasthan"),
    ("Jaipur Rural", "Rajasthan"),
    ("Jaisalmer", "Rajasthan"),
    ("Jalore", "Rajasthan"),
    ("Jhalawar", "Rajasthan"),
    ("Jhunjhunu", "Rajasthan"),
    ("Jodhpur", "Rajasthan"),
    ("Jodhpur Rural", "Rajasthan"),
    ("Karauli", "Rajasthan"),
    ("Kekri", "Rajasthan"),
    ("Khairthal-Tijara", "Rajasthan"),
    ("Kota", "Rajasthan"),
    ("Kotputli-Behror", "Rajasthan"),
    ("Nagaur", "Rajasthan"),
    ("Neem Ka Thana", "Rajasthan"),
    ("Pali", "Rajasthan"),
    ("Phalodi", "Rajasthan"),
    ("Pratapgarh", "Rajasthan"),
    ("Rajsamand", "Rajasthan"),
    ("Salumbar", "Rajasthan"),
    ("Sanchore", "Rajasthan"),
    ("Sawai Madhopur", "Rajasthan"),
    ("Shahpura", "Rajasthan"),
    ("Sikar", "Rajasthan"),
    ("Sirohi", "Rajasthan"),
    ("Sri Ganganagar", "Rajasthan"),
    ("Tonk", "Rajasthan"),
    ("Udaipur", "Rajasthan"),

    # =========================================================================
    # 22. Sikkim (6 districts)
    # =========================================================================
    ("Gangtok", "Sikkim"),
    ("Gyalshing", "Sikkim"),
    ("Mangan", "Sikkim"),
    ("Namchi", "Sikkim"),
    ("Pakyong", "Sikkim"),
    ("Soreng", "Sikkim"),

    # =========================================================================
    # 23. Tamil Nadu (38 districts)
    # =========================================================================
    ("Ariyalur", "Tamil Nadu"),
    ("Chengalpattu", "Tamil Nadu"),
    ("Chennai", "Tamil Nadu"),
    ("Coimbatore", "Tamil Nadu"),
    ("Cuddalore", "Tamil Nadu"),
    ("Dharmapuri", "Tamil Nadu"),
    ("Dindigul", "Tamil Nadu"),
    ("Erode", "Tamil Nadu"),
    ("Kallakurichi", "Tamil Nadu"),
    ("Kanchipuram", "Tamil Nadu"),
    ("Kanyakumari", "Tamil Nadu"),
    ("Karur", "Tamil Nadu"),
    ("Krishnagiri", "Tamil Nadu"),
    ("Madurai", "Tamil Nadu"),
    ("Mayiladuthurai", "Tamil Nadu"),
    ("Nagapattinam", "Tamil Nadu"),
    ("Namakkal", "Tamil Nadu"),
    ("Nilgiris", "Tamil Nadu"),
    ("Perambalur", "Tamil Nadu"),
    ("Pudukkottai", "Tamil Nadu"),
    ("Ramanathapuram", "Tamil Nadu"),
    ("Ranipet", "Tamil Nadu"),
    ("Salem", "Tamil Nadu"),
    ("Sivaganga", "Tamil Nadu"),
    ("Tenkasi", "Tamil Nadu"),
    ("Thanjavur", "Tamil Nadu"),
    ("Theni", "Tamil Nadu"),
    ("Thoothukudi", "Tamil Nadu"),
    ("Tiruchirappalli", "Tamil Nadu"),
    ("Tirunelveli", "Tamil Nadu"),
    ("Tirupathur", "Tamil Nadu"),
    ("Tiruppur", "Tamil Nadu"),
    ("Tiruvallur", "Tamil Nadu"),
    ("Tiruvannamalai", "Tamil Nadu"),
    ("Tiruvarur", "Tamil Nadu"),
    ("Vellore", "Tamil Nadu"),
    ("Viluppuram", "Tamil Nadu"),
    ("Virudhunagar", "Tamil Nadu"),

    # =========================================================================
    # 24. Telangana (33 districts)
    # =========================================================================
    ("Adilabad", "Telangana"),
    ("Bhadradri Kothagudem", "Telangana"),
    ("Hanumakonda", "Telangana"),
    ("Hyderabad", "Telangana"),
    ("Jagtial", "Telangana"),
    ("Jangaon", "Telangana"),
    ("Jayashankar Bhupalpally", "Telangana"),
    ("Jogulamba Gadwal", "Telangana"),
    ("Kamareddy", "Telangana"),
    ("Karimnagar", "Telangana"),
    ("Khammam", "Telangana"),
    ("Kumuram Bheem Asifabad", "Telangana"),
    ("Mahabubabad", "Telangana"),
    ("Mahabubnagar", "Telangana"),
    ("Mancherial", "Telangana"),
    ("Medak", "Telangana"),
    ("Medchal-Malkajgiri", "Telangana"),
    ("Mulugu", "Telangana"),
    ("Nagarkurnool", "Telangana"),
    ("Nalgonda", "Telangana"),
    ("Narayanpet", "Telangana"),
    ("Nirmal", "Telangana"),
    ("Nizamabad", "Telangana"),
    ("Peddapalli", "Telangana"),
    ("Rajanna Sircilla", "Telangana"),
    ("Ranga Reddy", "Telangana"),
    ("Sangareddy", "Telangana"),
    ("Siddipet", "Telangana"),
    ("Suryapet", "Telangana"),
    ("Vikarabad", "Telangana"),
    ("Wanaparthy", "Telangana"),
    ("Warangal", "Telangana"),
    ("Yadadri Bhuvanagiri", "Telangana"),

    # =========================================================================
    # 25. Tripura (8 districts)
    # =========================================================================
    ("Dhalai", "Tripura"),
    ("Gomati", "Tripura"),
    ("Khowai", "Tripura"),
    ("North Tripura", "Tripura"),
    ("Sepahijala", "Tripura"),
    ("South Tripura", "Tripura"),
    ("Unakoti", "Tripura"),
    ("West Tripura", "Tripura"),

    # =========================================================================
    # 26. Uttar Pradesh (75 districts)
    # =========================================================================
    ("Agra", "Uttar Pradesh"),
    ("Aligarh", "Uttar Pradesh"),
    ("Ambedkar Nagar", "Uttar Pradesh"),
    ("Amethi", "Uttar Pradesh"),
    ("Amroha", "Uttar Pradesh"),
    ("Auraiya", "Uttar Pradesh"),
    ("Ayodhya", "Uttar Pradesh"),
    ("Azamgarh", "Uttar Pradesh"),
    ("Baghpat", "Uttar Pradesh"),
    ("Bahraich", "Uttar Pradesh"),
    ("Ballia", "Uttar Pradesh"),
    ("Balrampur", "Uttar Pradesh"),
    ("Banda", "Uttar Pradesh"),
    ("Barabanki", "Uttar Pradesh"),
    ("Bareilly", "Uttar Pradesh"),
    ("Basti", "Uttar Pradesh"),
    ("Bhadohi", "Uttar Pradesh"),
    ("Bijnor", "Uttar Pradesh"),
    ("Budaun", "Uttar Pradesh"),
    ("Bulandshahr", "Uttar Pradesh"),
    ("Chandauli", "Uttar Pradesh"),
    ("Chitrakoot", "Uttar Pradesh"),
    ("Deoria", "Uttar Pradesh"),
    ("Etah", "Uttar Pradesh"),
    ("Etawah", "Uttar Pradesh"),
    ("Farrukhabad", "Uttar Pradesh"),
    ("Fatehpur", "Uttar Pradesh"),
    ("Firozabad", "Uttar Pradesh"),
    ("Gautam Buddha Nagar", "Uttar Pradesh"),
    ("Ghaziabad", "Uttar Pradesh"),
    ("Ghazipur", "Uttar Pradesh"),
    ("Gonda", "Uttar Pradesh"),
    ("Gorakhpur", "Uttar Pradesh"),
    ("Hamirpur", "Uttar Pradesh"),
    ("Hapur", "Uttar Pradesh"),
    ("Hardoi", "Uttar Pradesh"),
    ("Hathras", "Uttar Pradesh"),
    ("Jalaun", "Uttar Pradesh"),
    ("Jaunpur", "Uttar Pradesh"),
    ("Jhansi", "Uttar Pradesh"),
    ("Kannauj", "Uttar Pradesh"),
    ("Kanpur Dehat", "Uttar Pradesh"),
    ("Kanpur Nagar", "Uttar Pradesh"),
    ("Kasganj", "Uttar Pradesh"),
    ("Kaushambi", "Uttar Pradesh"),
    ("Kushinagar", "Uttar Pradesh"),
    ("Lakhimpur Kheri", "Uttar Pradesh"),
    ("Lalitpur", "Uttar Pradesh"),
    ("Lucknow", "Uttar Pradesh"),
    ("Maharajganj", "Uttar Pradesh"),
    ("Mahoba", "Uttar Pradesh"),
    ("Mainpuri", "Uttar Pradesh"),
    ("Mathura", "Uttar Pradesh"),
    ("Mau", "Uttar Pradesh"),
    ("Meerut", "Uttar Pradesh"),
    ("Mirzapur", "Uttar Pradesh"),
    ("Moradabad", "Uttar Pradesh"),
    ("Muzaffarnagar", "Uttar Pradesh"),
    ("Pilibhit", "Uttar Pradesh"),
    ("Pratapgarh", "Uttar Pradesh"),
    ("Prayagraj", "Uttar Pradesh"),
    ("Raebareli", "Uttar Pradesh"),
    ("Rampur", "Uttar Pradesh"),
    ("Saharanpur", "Uttar Pradesh"),
    ("Sambhal", "Uttar Pradesh"),
    ("Sant Kabir Nagar", "Uttar Pradesh"),
    ("Shahjahanpur", "Uttar Pradesh"),
    ("Shamli", "Uttar Pradesh"),
    ("Shravasti", "Uttar Pradesh"),
    ("Siddharthnagar", "Uttar Pradesh"),
    ("Sitapur", "Uttar Pradesh"),
    ("Sonbhadra", "Uttar Pradesh"),
    ("Sultanpur", "Uttar Pradesh"),
    ("Unnao", "Uttar Pradesh"),
    ("Varanasi", "Uttar Pradesh"),

    # =========================================================================
    # 27. Uttarakhand (13 districts)
    # =========================================================================
    ("Almora", "Uttarakhand"),
    ("Bageshwar", "Uttarakhand"),
    ("Chamoli", "Uttarakhand"),
    ("Champawat", "Uttarakhand"),
    ("Dehradun", "Uttarakhand"),
    ("Haridwar", "Uttarakhand"),
    ("Nainital", "Uttarakhand"),
    ("Pauri Garhwal", "Uttarakhand"),
    ("Pithoragarh", "Uttarakhand"),
    ("Rudraprayag", "Uttarakhand"),
    ("Tehri Garhwal", "Uttarakhand"),
    ("Udham Singh Nagar", "Uttarakhand"),
    ("Uttarkashi", "Uttarakhand"),

    # =========================================================================
    # 28. West Bengal (23 districts)
    # =========================================================================
    ("Alipurduar", "West Bengal"),
    ("Bankura", "West Bengal"),
    ("Birbhum", "West Bengal"),
    ("Cooch Behar", "West Bengal"),
    ("Dakshin Dinajpur", "West Bengal"),
    ("Darjeeling", "West Bengal"),
    ("Hooghly", "West Bengal"),
    ("Howrah", "West Bengal"),
    ("Jalpaiguri", "West Bengal"),
    ("Jhargram", "West Bengal"),
    ("Kalimpong", "West Bengal"),
    ("Kolkata", "West Bengal"),
    ("Malda", "West Bengal"),
    ("Murshidabad", "West Bengal"),
    ("Nadia", "West Bengal"),
    ("North 24 Parganas", "West Bengal"),
    ("Paschim Bardhaman", "West Bengal"),
    ("Paschim Medinipur", "West Bengal"),
    ("Purba Bardhaman", "West Bengal"),
    ("Purba Medinipur", "West Bengal"),
    ("Purulia", "West Bengal"),
    ("South 24 Parganas", "West Bengal"),
    ("Uttar Dinajpur", "West Bengal"),

    # =========================================================================
    # 29. Andaman and Nicobar Islands (3 districts)
    # =========================================================================
    ("Nicobar", "Andaman and Nicobar"),
    ("North and Middle Andaman", "Andaman and Nicobar"),
    ("South Andaman", "Andaman and Nicobar"),

    # =========================================================================
    # 30. Chandigarh (1 district)
    # =========================================================================
    ("Chandigarh", "Chandigarh"),

    # =========================================================================
    # 31. Dadra and Nagar Haveli and Daman and Diu (3 districts)
    # =========================================================================
    ("Dadra and Nagar Haveli", "Dadra and Nagar Haveli and Daman and Diu"),
    ("Daman", "Dadra and Nagar Haveli and Daman and Diu"),
    ("Diu", "Dadra and Nagar Haveli and Daman and Diu"),

    # =========================================================================
    # 32. Delhi (11 districts)
    # =========================================================================
    ("Central Delhi", "Delhi"),
    ("East Delhi", "Delhi"),
    ("New Delhi", "Delhi"),
    ("North Delhi", "Delhi"),
    ("North East Delhi", "Delhi"),
    ("North West Delhi", "Delhi"),
    ("Shahdara", "Delhi"),
    ("South Delhi", "Delhi"),
    ("South East Delhi", "Delhi"),
    ("South West Delhi", "Delhi"),
    ("West Delhi", "Delhi"),

    # =========================================================================
    # 33. Jammu and Kashmir (20 districts)
    # =========================================================================
    ("Anantnag", "Jammu and Kashmir"),
    ("Bandipora", "Jammu and Kashmir"),
    ("Baramulla", "Jammu and Kashmir"),
    ("Budgam", "Jammu and Kashmir"),
    ("Doda", "Jammu and Kashmir"),
    ("Ganderbal", "Jammu and Kashmir"),
    ("Jammu", "Jammu and Kashmir"),
    ("Kathua", "Jammu and Kashmir"),
    ("Kishtwar", "Jammu and Kashmir"),
    ("Kulgam", "Jammu and Kashmir"),
    ("Kupwara", "Jammu and Kashmir"),
    ("Poonch", "Jammu and Kashmir"),
    ("Pulwama", "Jammu and Kashmir"),
    ("Rajouri", "Jammu and Kashmir"),
    ("Ramban", "Jammu and Kashmir"),
    ("Reasi", "Jammu and Kashmir"),
    ("Samba", "Jammu and Kashmir"),
    ("Shopian", "Jammu and Kashmir"),
    ("Srinagar", "Jammu and Kashmir"),
    ("Udhampur", "Jammu and Kashmir"),

    # =========================================================================
    # 34. Ladakh (2 districts)
    # =========================================================================
    ("Kargil", "Ladakh"),
    ("Leh", "Ladakh"),

    # =========================================================================
    # 35. Lakshadweep (1 district)
    # =========================================================================
    ("Lakshadweep", "Lakshadweep"),

    # =========================================================================
    # 36. Puducherry (4 districts)
    # =========================================================================
    ("Karaikal", "Puducherry"),
    ("Mahe", "Puducherry"),
    ("Puducherry", "Puducherry"),
    ("Yanam", "Puducherry"),
]

# Primary crops per State / UT where power weeders and inter-cultivators are heavily utilized
STATE_CROPS = {
    "Andhra Pradesh": ["Rice", "Cotton", "Chilli", "Sugarcane"],
    "Arunachal Pradesh": ["Ginger", "Turmeric", "Maize", "Vegetables"],
    "Assam": ["Tea", "Rice", "Jute", "Vegetables"],
    "Bihar": ["Rice", "Wheat", "Maize", "Sugarcane"],
    "Chhattisgarh": ["Rice", "Soybean", "Maize", "Vegetables"],
    "Goa": ["Cashew", "Coconut", "Rice"],
    "Gujarat": ["Cotton", "Groundnut", "Castor", "Cumin"],
    "Haryana": ["Wheat", "Sugarcane", "Mustard", "Cotton"],
    "Himachal Pradesh": ["Apple Orchards", "Maize", "Vegetables", "Ginger"],
    "Jharkhand": ["Rice", "Vegetables", "Maize", "Pulses"],
    "Karnataka": ["Sugarcane", "Coconut", "Arecanut", "Maize"],
    "Kerala": ["Coconut", "Rubber", "Arecanut", "Spices"],
    "Madhya Pradesh": ["Soybean", "Wheat", "Cotton", "Garlic"],
    "Maharashtra": ["Sugarcane", "Cotton", "Soybean", "Onion"],
    "Manipur": ["Rice", "Vegetables", "Ginger", "Pineapple"],
    "Meghalaya": ["Ginger", "Turmeric", "Maize", "Vegetables"],
    "Mizoram": ["Ginger", "Turmeric", "Vegetables", "Maize"],
    "Nagaland": ["Maize", "Ginger", "Vegetables", "Cardamom"],
    "Odisha": ["Rice", "Vegetables", "Sugarcane", "Groundnut"],
    "Punjab": ["Wheat", "Sugarcane", "Cotton", "Maize"],
    "Rajasthan": ["Mustard", "Cotton", "Bajra", "Groundnut"],
    "Sikkim": ["Cardamom", "Ginger", "Vegetables", "Buckwheat"],
    "Tamil Nadu": ["Rice", "Sugarcane", "Coconut", "Banana"],
    "Telangana": ["Cotton", "Rice", "Chilli", "Turmeric"],
    "Tripura": ["Rubber", "Rice", "Vegetables", "Pineapple"],
    "Uttar Pradesh": ["Sugarcane", "Wheat", "Rice", "Potato"],
    "Uttarakhand": ["Sugarcane", "Rice", "Vegetables", "Maize"],
    "West Bengal": ["Rice", "Jute", "Vegetables", "Potato"],
    "Andaman and Nicobar": ["Coconut", "Arecanut", "Vegetables"],
    "Andaman and Nicobar Islands": ["Coconut", "Arecanut", "Vegetables"],
    "Chandigarh": ["Vegetables", "Horticulture"],
    "Dadra and Nagar Haveli and Daman and Diu": ["Rice", "Vegetables", "Sugarcane"],
    "Delhi": ["Vegetables", "Flowers", "Horticulture"],
    "Jammu and Kashmir": ["Apple Orchards", "Saffron", "Maize", "Vegetables"],
    "Ladakh": ["Barley", "Vegetables", "Apricot Orchards"],
    "Lakshadweep": ["Coconut", "Horticulture"],
    "Puducherry": ["Rice", "Sugarcane", "Coconut"],
}

# Hindi translations of Indian States and Union Territories (Devanagari script)
HINDI_STATES = {
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Arunachal Pradesh": "अरुणाचल प्रदेश",
    "Assam": "असम",
    "Bihar": "बिहार",
    "Chhattisgarh": "छत्तीसगढ़",
    "Goa": "गोवा",
    "Gujarat": "गुजरात",
    "Haryana": "हरियाणा",
    "Himachal Pradesh": "हिमाचल प्रदेश",
    "Jharkhand": "झारखंड",
    "Karnataka": "कर्नाटक",
    "Kerala": "केरल",
    "Madhya Pradesh": "मध्य प्रदेश",
    "Maharashtra": "महाराष्ट्र",
    "Manipur": "मणिपुर",
    "Meghalaya": "मेघालय",
    "Mizoram": "मिज़ोरम",
    "Nagaland": "नागालैंड",
    "Odisha": "ओडिशा",
    "Punjab": "पंजाब",
    "Rajasthan": "राजस्थान",
    "Sikkim": "सिक्किम",
    "Tamil Nadu": "तमिलनाडु",
    "Telangana": "तेलंगाना",
    "Tripura": "त्रिपुरा",
    "Uttar Pradesh": "उत्तर प्रदेश",
    "Uttarakhand": "उत्तराखंड",
    "West Bengal": "पश्चिम बंगाल",
    "Andaman and Nicobar": "अंडमान और निकोबार",
    "Andaman and Nicobar Islands": "अंडमान और निकोबार द्वीप समूह",
    "Chandigarh": "चंडीगढ़",
    "Dadra and Nagar Haveli and Daman and Diu": "दादरा और नगर हवेली और दमन और दीव",
    "Delhi": "दिल्ली",
    "Jammu and Kashmir": "जम्मू और कश्मीर",
    "Ladakh": "लद्दाख",
    "Lakshadweep": "लक्षद्वीप",
    "Puducherry": "पुदुचेरी",
}
