"""Initial product catalog seed data for KrishiGears.

Mirrors /app/frontend/src/data/catalog.js — products and categories.
Used to populate MongoDB on first startup.
"""
from typing import List, Dict, Any

RKA = "https://royalkissanagro.com/wp-content/uploads"

COVER = {
    "weeder": f"{RKA}/2025/10/weeder-1.webp",
    "brushCutter": f"{RKA}/2025/10/brush-cutter.webp",
    "chainsaw": f"{RKA}/2025/10/chainsaw.webp",
    "earthAuger": f"{RKA}/2025/10/earth-auger.webp",
    "waterPump": f"{RKA}/2025/10/water-pump.webp",
    "hosePipe": f"{RKA}/2025/10/hosepipe.webp",
    "engine": f"{RKA}/2025/10/engine.webp",
    "sprayer": f"{RKA}/2025/10/sprayer.webp",
    "chaffCutter": f"{RKA}/2025/10/chaff-cuter.webp",
    "maizeThresher": f"{RKA}/2025/10/maize-trasher.webp",
    "reaper": f"{RKA}/2025/11/reaper.webp",
    "grassMower": f"{RKA}/2025/10/Grass-Stubble-Mower.webp",
    "miniInter": f"{RKA}/2025/10/Mini-Intercultivator.webp",
    "babyWeeder": f"{RKA}/2025/10/baby-weeder.webp",
    "seeder": f"{RKA}/2025/10/seeders.webp",
    "crankshaft": f"{RKA}/2025/10/Crankshaft.webp",
    "piston": f"{RKA}/2025/10/Piston-and-Ring.webp",
    "carburetor": f"{RKA}/2025/10/Carburetor.webp",
    "recoil": f"{RKA}/2025/10/recoil-starter-assembly.webp",
}

_BASE_FEATURES = [
    "Authorized Royal Kissan Agro product",
    "Backed by manufacturer warranty",
    "PAN India delivery from KrishiGears",
    "Genuine spare parts availability",
]
_BASE_BENEFITS = [
    "Saves significant manual labour",
    "Reduces operating cost over time",
    "FMTTI-tested durability",
]
WARRANTY_STD = "12 months manufacturer warranty + KrishiGears after-sales service network."
WARRANTY_6 = "6 months manufacturer warranty + KrishiGears after-sales service network."
WARRANTY_SPARE = "3 months replacement on manufacturing defects"


def _features(extra: List[str] = []) -> List[str]:
    return _BASE_FEATURES + extra


def _benefits(extra: List[str] = []) -> List[str]:
    return _BASE_BENEFITS + extra


PRODUCTS: List[Dict[str, Any]] = [
    # POWER WEEDERS
    {"slug":"rk-icp-up170-sh","category":"power-weeders","name":"Ultra-Premium Petrol Power Weeder — 5.17 HP","model":"RK-ICP-UP170-SH","badges":["SRFMTTI Tested","Subsidy Approved"],"images":[f"{RKA}/2025/11/RK-ICP-UP170-SH-1.webp"],"specs":{"Model":"RK-ICP-UP170-SH","Engine":"170F, 4-Stroke, Air Cooled","Displacement":"212 CC","Power":"5.17 HP","Fuel":"Petrol","Fuel Tank":"3.6 L","Start":"Recoil","Feature":"Shock Absorber Handle"},"features":_features(["Shock absorber handle reduces vibration","Premium 170F engine","Subsidy approved (SRFMTTI tested)"]),"applications":["Sugarcane","Vegetables","Horticulture","Inter-row weeding"],"benefits":_benefits(["Government subsidy eligible"]),"warranty":WARRANTY_STD},
    {"slug":"rk-177f-wolf","category":"power-weeders","name":"5.44 HP Petrol Power Weeder — RK-177F-WOLF","model":"RK-177F-WOLF","badges":["Ultra Premium"],"images":[f"{RKA}/2025/11/RK-170F-1.webp"],"specs":{"Model":"RK-177F-WOLF","Engine":"177F, 4-Stroke, Air Cooled","Displacement":"270 CC","Power":"5.44 HP / 5.5 kW","Fuel":"Petrol","Fuel Tank":"4 L","Feature":"Low Vibration Design"},"features":_features(["High torque for hard fields","Low-vibration ergonomic build","Large 4L fuel tank for long runtime"]),"applications":["Sugarcane","Vegetables","Hard / uneven fields"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-170f","category":"power-weeders","name":"5.5 HP Petrol Power Weeder — RK-170F","model":"RK-170F","badges":["FMTTI Tested","Subsidy Approved"],"images":[f"{RKA}/2025/11/NB-ICP-C170-LCE.webp"],"specs":{"Model":"RK-170F","Engine":"170F, 4-Stroke","Displacement":"212 CC","Power":"5.5 HP","Fuel":"Petrol","Fuel Tank":"3.6 L"},"features":_features(["FMTTI tested & subsidy approved","Trusted 212CC engine","Easy electric / recoil start"]),"applications":["Paddy","Wheat","Vegetables","Sugarcane"],"benefits":_benefits(["Government subsidy eligible"]),"warranty":WARRANTY_STD},
    {"slug":"rk-icp-p177-lde","category":"power-weeders","name":"7.5 HP Petrol Power Weeder — RK-ICP-P177-LDE","model":"RK-ICP-P177-LDE","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-ICP-P177-LDE.webp"],"specs":{"Model":"RK-ICP-P177-LDE","Engine":"177F, 4-Stroke, Air Cooled","Displacement":"270 CC","Power":"7.5 HP","Fuel":"Petrol","Blades":"40 Blades"},"features":_features(["40-blade rotor for deep tilling","Premium 270cc air-cooled engine","Electric start option"]),"applications":["Large vegetable plots","Horticulture","Heavy-duty inter-cultivation"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-icp-p170-lde","category":"power-weeders","name":"5.5 HP Petrol Power Weeder — RK-ICP-P170-LDE (ATV Tyres)","model":"RK-ICP-P170-LDE","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-ICP-P170-LDE.webp"],"specs":{"Model":"RK-ICP-P170-LDE","Engine":"4-Stroke","Power":"5.5 HP","Fuel":"Petrol","Fuel Tank":"4 L","Tyres":"ATV"},"features":_features(["Rugged ATV tyres for uneven terrain","Electric start helps women & senior farmers","4L tank for long runs"]),"applications":["Narrow rows","Vegetable beds","Polyhouses"],"benefits":_benefits(["Halves weeding time"]),"warranty":WARRANTY_STD},
    {"slug":"np-icp-c177","category":"power-weeders","name":"Classic 7.5 HP Petrol Power Weeder — NP-ICP-C177","model":"NP-ICP-C177","badges":["Classic"],"images":[f"{RKA}/2025/11/NP-ICP-C177.webp"],"specs":{"Model":"NP-ICP-C177","Engine":"4-Stroke, Air Cooling","Displacement":"270 CC","Power":"7.5 HP","Blades":"32 Blades","Handle":"Kama Handle"},"features":_features(["32-blade rotor","Kama handle for stable grip","Recoil start"]),"applications":["Horticulture","Vegetable cultivation"],"benefits":_benefits(["Smooth handling, low maintenance"]),"warranty":WARRANTY_STD},
    {"slug":"rk-173f-diesel","category":"power-weeders","name":"Ultra Premium 7 HP Diesel Power Weeder — RK-173F","model":"RK-173F","badges":["FMTTI Tested","Subsidy Approved"],"images":[f"{RKA}/2025/11/RK-173F-1.webp"],"specs":{"Model":"RK-173F","Engine":"4-Stroke Diesel, Air Cooled","Displacement":"247 CC","Power":"7 HP / 4 kW @ 3200 RPM","Fuel":"Diesel"},"features":_features(["Strong torque for monsoon paddy fields","Diesel efficiency for long hours","Subsidy approved"]),"applications":["Paddy fields","Heavy soil","Wheat","Sugarcane"],"benefits":_benefits(["Government subsidy eligible","High fuel efficiency"]),"warranty":WARRANTY_STD},
    {"slug":"rk-icd-up186-sh","category":"power-weeders","name":"Ultra Premium 7.93 HP Diesel Power Weeder — RK-ICD-UP186-SH","model":"RK-ICD-UP186-SH","badges":["SRFMTTI Tested","Subsidy Approved"],"images":[f"{RKA}/2025/11/RK-ICD-UP186-SH-1.webp"],"specs":{"Model":"RK-ICD-UP186-SH","Engine":"186F Diesel, 4-Stroke","Power":"7.93 HP","Fuel":"Diesel","Start":"Electric Start","Feature":"Double Fender, Shock Absorber"},"features":_features(["Electric start convenience","Double fender — safer & cleaner","Premium shock absorber handle"]),"applications":["Compact moisture-rich farms (Kerala, coastal)","Paddy"],"benefits":_benefits(["Subsidy eligible","Fuel efficient"]),"warranty":WARRANTY_STD},
    {"slug":"nb-icd-c186","category":"power-weeders","name":"Classic 8.5 HP Diesel Power Weeder — NB-ICD-C186","model":"NB-ICD-C186","badges":["Classic"],"images":[f"{RKA}/2025/11/NB-ICD-C186.webp"],"specs":{"Model":"NB-ICD-C186","Engine":"4-Stroke Diesel, Air Cooled","Displacement":"418 CC","Power":"8.5 HP","Fuel":"Diesel"},"features":_features(["High-power 418cc engine","Built for large farms","Easy-grip handle"]),"applications":["Large farms","Heavy fields","Commercial use"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"nb-icd-c178","category":"power-weeders","name":"Classic 7.5 HP Diesel Power Weeder — NB-ICD-C178","model":"NB-ICD-C178","badges":["Classic"],"images":[f"{RKA}/2025/11/NB-ICD-C178.webp"],"specs":{"Model":"NB-ICD-C178","Engine":"4-Stroke Diesel, Air Cooled","Displacement":"296 CC","Power":"7.5 HP","Fuel Tank":"3.5 L"},"features":_features(["Stable engine speed","Firm grip","Smooth inter-row cultivation"]),"applications":["Grape","Onion","Inter-row cultivation"],"benefits":_benefits(),"warranty":WARRANTY_STD},

    # BRUSH CUTTERS
    {"slug":"rk-bc-up52","category":"brush-cutters","name":"Ultra Premium 2.5 HP 2-Stroke Brush Cutter — RK-BC-UP52","model":"RK-BC-UP52-SP/BP","badges":["SRFMTTI Tested","Subsidy Approved"],"images":[f"{RKA}/2025/11/Ultra-Premium-2.5HP-2-Stroke-Brush-Cutter-_-RK-BC-UP52-SP-_-BP-_-80T-2T-TAP-N-GO-_-SUBSIDY-APPROVED-_-Royal-Kissan.png"],"specs":{"Model":"RK-BC-UP52-SP / BP","Engine":"2-Stroke Petrol","Displacement":"52 CC","Power":"2.5 HP","Blades":"80T, 2T & TAP N GO","Mounting":"Side-pack / Back-pack"},"features":_features(["High power-to-weight 2-stroke","Multiple blade options","SRFMTTI tested & subsidy approved","Side & backpack mounting"]),"applications":["Grass & weed cutting","Paddy stubble","Bush trimming","Plantation"],"benefits":_benefits(["Government subsidy eligible"]),"warranty":WARRANTY_6},
    {"slug":"rk-bc-up43","category":"brush-cutters","name":"Ultra Premium 1.75 HP 2-Stroke Brush Cutter — RK-BC-UP43-SP","model":"RK-BC-UP43-SP","badges":["SRFMTTI Tested","Subsidy Approved"],"images":[f"{RKA}/2025/11/RK-BC-UP43-SP.webp"],"specs":{"Model":"RK-BC-UP43-SP","Engine":"2-Stroke Petrol","Displacement":"43 CC","Power":"1.75 HP","Blades":"80T, 2T & TAP N GO"},"features":_features(["Lightweight 2-stroke","Anti-vibration design","Subsidy approved"]),"applications":["Grass","Weeds","Light bush"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"rk-bc-up35","category":"brush-cutters","name":"Ultra Premium 1.6 HP 4-Stroke Brush Cutter — RK-BC-UP35","model":"RK-BC-UP35-BP/SP","badges":["Ultra Premium"],"images":[f"{RKA}/2025/11/Ultra-Premium-1.6HP-4-Stroke-Brush-Cutter-_-RK-BC-UP35-BP_SP-_-80T-2T-TAP-N-GO-_-35.8CC-_-Royal-Kissan.png"],"specs":{"Model":"RK-BC-UP35-BP/SP","Engine":"4-Stroke Petrol","Displacement":"35.8 CC","Power":"1.6 HP","Blades":"80T, 2T & TAP N GO"},"features":_features(["4-stroke fuel efficient","Lower emissions","Quiet operation"]),"applications":["Residential / near-house areas","Vegetable plots"],"benefits":_benefits(["Lower fuel cost"]),"warranty":WARRANTY_6},
    {"slug":"rk-bc-p50","category":"brush-cutters","name":"Premium 3 HP 4-Stroke Brush Cutter — RK-BC-P50-SP","model":"RK-BC-P50-SP","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-BC-P50-SP.webp"],"specs":{"Model":"RK-BC-P50-SP","Engine":"4-Stroke Petrol","Displacement":"50 CC","Power":"3 HP","Blades":"80T, 3T & TAP N GO"},"features":_features(["Premium 3HP power","3T blade for tough vegetation","4-stroke efficiency"]),"applications":["Thick weeds","Heavy grass","Land clearing"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"nsm-bc-c52","category":"brush-cutters","name":"Classic 2.5 HP 2-Stroke Brush Cutter — NSM-BC-C52","model":"NSM-BC-C52-SP/BP","badges":["Classic"],"images":[f"{RKA}/2025/11/NSM-BC-C52-SP-BP.webp"],"specs":{"Model":"NSM-BC-C52-SP/BP","Engine":"2-Stroke Petrol","Displacement":"52 CC","Power":"2.5 HP"},"features":_features(["Classic affordable model","Rugged build for daily use"]),"applications":["Grass","Stubble","General farm clearing"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"nsm-bc-c43","category":"brush-cutters","name":"Classic 1.75 HP 2-Stroke Brush Cutter — NSM-BC-C43","model":"NSM-BC-C43-SP/BP","badges":["Classic"],"images":[f"{RKA}/2025/11/NSM-BC-C43-SP-BP.webp"],"specs":{"Model":"NSM-BC-C43-SP/BP","Engine":"2-Stroke Petrol","Displacement":"43 CC","Power":"1.75 HP","Blades":"80T, 2T & TAP N GO"},"features":_features(["Entry-level reliable cutter","Light weight"]),"applications":["Grass cutting","Light weeding"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"nsm-bc-c35","category":"brush-cutters","name":"Classic 1.75 HP 4-Stroke OHV Brush Cutter — NSM-BC-C35","model":"NSM-BC-C35-SP/BP","badges":["Classic"],"images":[f"{RKA}/2025/11/NSM-BC-C35-SP-BP.webp"],"specs":{"Model":"NSM-BC-C35-SP/BP","Engine":"4-Stroke OHV Petrol","Displacement":"35 CC","Power":"1.75 HP","Blades":"80T, 2T & TAP N GO"},"features":_features(["4-stroke OHV — better fuel economy","Lower noise"]),"applications":["Grass","Light bushes"],"benefits":_benefits(),"warranty":WARRANTY_6},

    # CHAIN SAWS
    {"slug":"rk-csp-up58","category":"chain-saws","name":"Ultra Premium Chain Saw 58cc / 3.2 HP — RK-CSP-UP58","model":"RK-CSP-UP58-18/22","badges":["Ultra Premium"],"images":[f"{RKA}/2025/11/RK-CSP-UP58-18-22.webp"],"specs":{"Model":"RK-CSP-UP58-18/22","Engine":"2-Stroke Petrol","Displacement":"58 CC","Power":"3.2 HP","Bar Length":"18\" or 22\"","Carburetor":"2-Pipe","Blade":"Diamond"},"features":_features(["2-pipe carburetor for stronger fuel mix","Diamond blade for clean cuts","18\" / 22\" bar options","Up to 45 min continuous use"]),"applications":["Tree felling","Firewood","Orchard pruning"],"benefits":_benefits(["Fuel-efficient 2-stroke"]),"warranty":WARRANTY_6},
    {"slug":"rk-csp-up63","category":"chain-saws","name":"Ultra Premium 3.5 HP Chain Saw — RK-CSP-UP63","model":"RK-CSP-UP63-18/22","badges":["Ultra Premium"],"images":[f"{RKA}/2025/11/RK-CSP-UP63-18-22.webp"],"specs":{"Model":"RK-CSP-UP63-18/22","Engine":"2-Stroke Petrol","Displacement":"63 CC","Power":"3.5 HP","Bar Length":"18\" or 22\"","Carburetor":"2-Pipe"},"features":_features(["Highest power in our range","Heavy-duty professional cutting"]),"applications":["Large tree felling","Forestry","Commercial wood cutting"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"nsm-csp-c58","category":"chain-saws","name":"Classic 3.2 HP Chain Saw — NSM-CSP-C58","model":"NSM-CSP-C58-18/22","badges":["Classic"],"images":[f"{RKA}/2025/11/NSM-CSP-C58-18-22.webp"],"specs":{"Model":"NSM-CSP-C58-18/22","Engine":"2-Stroke Petrol","Displacement":"58 CC","Power":"3.2 HP","Bar Length":"18\" or 22\""},"features":_features(["Affordable classic series","Rugged design"]),"applications":["General wood cutting","Pruning","Farm maintenance"],"benefits":_benefits(),"warranty":WARRANTY_6},

    # EARTH AUGERS
    {"slug":"rk-ea-p68","category":"earth-augers","name":"Royal Kissan Premium Earth Auger 3.5 HP — RK-EA-P68","model":"RK-EA-P68","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-EA-P68.webp"],"specs":{"Model":"RK-EA-P68","Engine":"Single-Cylinder, 2-Stroke","Displacement":"68 CC","Power":"3.5 HP"},"features":_features(["High torque for hard soil","Double gearbox","Butterfly handle for low vibration"]),"applications":["Tree planting","Fence posts","Drip irrigation pits","Borewell pre-drilling"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"rk-ea-p52","category":"earth-augers","name":"Royal Kissan Premium Earth Auger 2.5 HP — RK-EA-P52","model":"RK-EA-P52","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-EA-P52.webp"],"specs":{"Model":"RK-EA-P52","Engine":"2-Stroke","Displacement":"52 CC","Power":"2.5 HP","Fuel Tank":"1 L"},"features":_features(["Compact & lightweight","Easy recoil start"]),"applications":["Sapling planting","Small fencing jobs"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"nsm-ea-p68","category":"earth-augers","name":"Royal Kissan Earth Auger 3.5 HP — NSM-EA-P68","model":"NSM-EA-P68","badges":["Classic"],"images":[f"{RKA}/2025/11/NSM-EA-P68.webp"],"specs":{"Model":"NSM-EA-P68","Engine":"2-Stroke","Displacement":"68 CC","Power":"3.5 HP","Fuel Tank":"1 L"},"features":_features(["Reliable 68cc engine","Air-cooled"]),"applications":["Plantation","Fencing","Horticulture"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"nsm-ea-p52","category":"earth-augers","name":"Royal Kissan Earth Auger 2.5 HP — NSM-EA-P52","model":"NSM-EA-P52","badges":["Classic"],"images":[f"{RKA}/2025/11/NSM-EA-P52.webp"],"specs":{"Model":"NSM-EA-P52","Engine":"Single-Cylinder, 2-Stroke","Displacement":"52 CC","Power":"2.5 HP"},"features":_features(["Single-cylinder reliability","Solo operation"]),"applications":["Sapling planting","Light fencing"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"nsm-ea-p55","category":"earth-augers","name":"3 HP Earth Auger — NSM-EA-P55 (4-Stroke)","model":"NSM-EA-P55","badges":["Premium"],"images":[f"{RKA}/2025/11/NSM-EA-P55.webp"],"specs":{"Model":"NSM-EA-P55","Engine":"4-Stroke","Displacement":"55 CC","Power":"3 HP","Fuel Tank":"2 L"},"features":_features(["4-stroke fuel-efficient engine","2L tank for long runs"]),"applications":["Large plantation projects","Drip irrigation"],"benefits":_benefits(["Lower fuel cost"]),"warranty":WARRANTY_6},

    # WATER PUMPS
    {"slug":"rk-wp-up3","category":"water-pumps","name":"Ultra Premium 5.1 HP Water Pump — RK-WP-UP3","model":"RK-WP-UP3","badges":["Ultra Premium"],"images":[f"{RKA}/2025/11/RKS-30.webp"],"specs":{"Model":"RK-WP-UP3","Engine":"4-Stroke Petrol","Displacement":"212 CC","Power":"5.1 HP","Fuel":"Petrol"},"features":_features(["Strong suction (up to 30m)","Corrosion-resistant parts","Low fuel consumption"]),"applications":["Field irrigation","Canal-fed paddy","Banana / sugarcane"],"benefits":_benefits(["Halves irrigation time"]),"warranty":WARRANTY_STD},
    {"slug":"rk-wp-p03","category":"water-pumps","name":"Premium 5.1 HP 4-Stroke Water Pump — RK-WP-P03","model":"RK-WP-P03","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-WP-P03.webp"],"specs":{"Model":"RK-WP-P03","Engine":"4-Stroke Petrol","Displacement":"212 CC","Power":"5.1 HP"},"features":_features(["High head capacity","Reliable 4-stroke"]),"applications":["Paddy","Wheat","Orchards"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-wp-p02","category":"water-pumps","name":"Premium 5.1 HP Water Pump — RK-WP-P02","model":"RK-WP-P02","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-WP-P02-1.webp"],"specs":{"Model":"RK-WP-P02","Engine":"4-Stroke Petrol","Displacement":"212 CC","Power":"5.1 HP"},"features":_features(["Steady flow","Cool running"]),"applications":["Large field irrigation","Cotton & chili"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-wp-p1-5","category":"water-pumps","name":"Premium 2.5 HP Compact Water Pump — RK-WP-P1.5","model":"RK-WP-P1.5","badges":["Premium"],"images":[f"{RKA}/2025/11/RK-WP-P1-5.webp"],"specs":{"Model":"RK-WP-P1.5","Engine":"4-Stroke Petrol","Displacement":"98 CC","Power":"2.5 HP"},"features":_features(["Compact & lightweight","Easy to carry across plots"]),"applications":["Small farms","Garden irrigation"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-pw-wp-d80","category":"water-pumps","name":"Power Tiller Water Pump Attachment — RK-PW-WP-D80","model":"RK-PW-WP-D80","badges":["Attachment"],"images":[f"{RKA}/2025/11/RK-PW-WP-D80.webp"],"specs":{"Model":"RK-PW-WP-D80","Type":"Gear Drive Diesel Attachment","Outlet Size":"3 inch / 80mm"},"features":_features(["Uses tiller PTO — no extra engine","High-flow heavy-duty","Gear drive reliability"]),"applications":["Large field irrigation","Firefighting","Wash-downs"],"benefits":_benefits(["Cost effective — reuses tiller engine"]),"warranty":WARRANTY_STD},
    {"slug":"rk-pw-wp-p80","category":"water-pumps","name":"Power Tiller Water Pump Attachment — RK-PW-WP-P80 (Petrol)","model":"RK-PW-WP-P80","badges":["Attachment"],"images":[f"{RKA}/2025/11/RK-PW-WP-P80.webp"],"specs":{"Model":"RK-PW-WP-P80","Type":"Petrol Attachment","Outlet Size":"3 inch / 80mm"},"features":_features(["PTO-driven","High discharge"]),"applications":["Heavy-duty irrigation"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-su80","category":"water-pumps","name":"Belt Drive Water Pump Attachment — RK-SU80","model":"RK-SU80","badges":["Attachment"],"images":[f"{RKA}/2025/11/RK-SU80.webp"],"specs":{"Model":"RK-SU80","Type":"Belt Drive","Outlet Size":"3 inch / 80mm"},"features":_features(["Universal belt drive","Fits common engines"]),"applications":["Field irrigation","Drainage"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"wqd10-11-075a","category":"water-pumps","name":"Submersible Sewage Pump 1 HP — WQD10-11-0.75A","model":"WQD10-11-0.75A","badges":["Submersible"],"images":[f"{RKA}/2025/11/WQD10-11-0-75A.webp"],"specs":{"Model":"WQD10-11-0.75A","Type":"Submersible Electric Sewage","Power":"1 HP"},"features":_features(["Clog-resistant impeller","Handles solids & sludge","Quiet operation"]),"applications":["Sewage drainage","Dirty water transfer","Flooded basements"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"wqd15-10-11a","category":"water-pumps","name":"Submersible Sewage Pump 1.5 HP — WQD15-10-1.1FA","model":"WQD15-10-1.1FA","badges":["Submersible"],"images":[f"{RKA}/2025/11/WQD15-10-1-1A.webp"],"specs":{"Model":"WQD15-10-1.1FA","Type":"Submersible Sewage","Power":"1.5 HP","Head":"15 M"},"features":_features(["15M head lift","Corrosion resistant"]),"applications":["Industrial sewage","Farm drainage"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"wqd15-15-15fa","category":"water-pumps","name":"Submersible Sewage Pump 1.5 kW — WQD15-15-1.5FA","model":"WQD15-15-1.5FA","badges":["Submersible"],"images":[f"{RKA}/2025/11/WQD15-15-1-5FA.webp"],"specs":{"Model":"WQD15-15-1.5FA","Type":"Submersible Sewage","Power":"1.5 kW","Head":"19 M","Flow Rate":"416 L/min"},"features":_features(["19M head","High 416 L flow rate","Heavy-duty"]),"applications":["Large industrial sewage","Municipal drainage"],"benefits":_benefits(),"warranty":WARRANTY_STD},

    # Other categories — single representative product each
    {"slug":"rk-reaper","category":"reapers","name":"Self-Propelled Paddy & Wheat Reaper","model":"RK-REAPER","badges":["Premium"],"images":[COVER["reaper"]],"specs":{"Type":"Self-Propelled Reaper","Application":"Paddy / Wheat","Power":"Petrol Engine"},"features":_features(["Fast crop cutting","Reduces harvest labour"]),"applications":["Paddy harvesting","Wheat harvesting"],"benefits":_benefits(["Cuts harvest time by 60%"]),"warranty":WARRANTY_STD},
    {"slug":"rk-chaff-cutter","category":"chaff-cutters","name":"Engine-Driven Chaff Cutter","model":"RK-CC","badges":["Premium"],"images":[COVER["chaffCutter"]],"specs":{"Type":"Chaff Cutter","Drive":"Engine / Electric Options"},"features":_features(["Shreds stalks finely","Heavy-duty blades"]),"applications":["Cattle fodder","Silage preparation"],"benefits":_benefits(["Better cattle feed","Saves hours of manual work"]),"warranty":WARRANTY_STD},
    {"slug":"rk-maize-thresher","category":"agricultural-engines","name":"Maize Thresher","model":"RK-MT","badges":["Premium"],"images":[COVER["maizeThresher"]],"specs":{"Type":"Maize Thresher","Application":"Maize / Corn"},"features":_features(["Clean separation","High throughput"]),"applications":["Maize threshing"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-grass-mower","category":"brush-cutters","name":"Grass Stubble Mower","model":"RK-GSM","badges":["Premium"],"images":[COVER["grassMower"]],"specs":{"Type":"Grass Stubble Mower"},"features":_features(["Clears leftover stubble","Fast field cleanup"]),"applications":["Post-harvest field cleaning"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-mini-inter","category":"mini-cultivators","name":"Mini Intercultivator","model":"RK-MI","badges":["Premium"],"images":[COVER["miniInter"]],"specs":{"Type":"Diesel Mini Intercultivator","Power":"Diesel Engine"},"features":_features(["Doubles sapling coverage","30% less manpower required"]),"applications":["Sapling planting","Inter-row cultivation"],"benefits":_benefits(["+15% higher yield in trials"]),"warranty":WARRANTY_STD},
    {"slug":"rk-baby-weeder","category":"power-weeders","name":"Baby Weeder","model":"RK-BW","badges":["Compact"],"images":[COVER["babyWeeder"]],"specs":{"Type":"Compact Baby Weeder"},"features":_features(["Lightweight","Easy for women & senior farmers"]),"applications":["Rice paddy","Small kitchen gardens"],"benefits":_benefits(["80% weed reduction (Punjab trial)"]),"warranty":WARRANTY_STD},
    {"slug":"rk-seeder","category":"seeders","name":"Manual / Power Seeder","model":"RK-S","badges":["Premium"],"images":[COVER["seeder"]],"specs":{"Type":"Seeder","Application":"Precision sowing"},"features":_features(["Uniform spacing","Multiple crops"]),"applications":["Vegetable sowing","Cereal sowing"],"benefits":_benefits(["Better germination rate"]),"warranty":WARRANTY_STD},
    {"slug":"rk-engine","category":"agricultural-engines","name":"Agricultural Engine (Petrol / Diesel / Kerosene)","model":"RK-ENG","badges":["Premium"],"images":[COVER["engine"]],"specs":{"Type":"Multi-fuel Agricultural Engine"},"features":_features(["Reliable starter","Long service life"]),"applications":["Power tillers","Water pumps","General farm power"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-sprayer-power","category":"power-sprayers","name":"Power Sprayer","model":"RK-PS","badges":["Premium"],"images":[COVER["sprayer"]],"specs":{"Type":"Engine-driven Power Sprayer","Application":"Plantations & large farms"},"features":_features(["High pressure","Even spray pattern","Long hose reach"]),"applications":["Plantations","Orchards","Vegetable spraying"],"benefits":_benefits(),"warranty":WARRANTY_STD},
    {"slug":"rk-sprayer-battery","category":"battery-sprayers","name":"Battery Knapsack Sprayer 16L","model":"RK-BS-16","badges":["Premium"],"images":[COVER["sprayer"]],"specs":{"Type":"Battery Knapsack Sprayer","Capacity":"16 L","Battery":"12V"},"features":_features(["Silent operation","Long battery life"]),"applications":["Fertilizer","Pesticide spraying"],"benefits":_benefits(["No fuel needed"]),"warranty":WARRANTY_STD},
    {"slug":"rk-hose-pipe","category":"agricultural-accessories","name":"Agricultural Hose Pipe (Heavy Duty)","model":"RK-HP","badges":["Accessory"],"images":[COVER["hosePipe"]],"specs":{"Type":"Heavy-duty hose pipe","Use":"Irrigation, washing"},"features":_features(["Flexible & durable","Leak resistant"]),"applications":["Tea plantations","Farm irrigation"],"benefits":_benefits(),"warranty":WARRANTY_6},
    {"slug":"rk-crankshaft","category":"agricultural-spare-parts","name":"Crankshaft — OEM Spare","model":"RK-CRANK","badges":["Spare"],"images":[COVER["crankshaft"]],"specs":{"Type":"Crankshaft","Grade":"OEM"},"features":_features(["Genuine OEM grade"]),"applications":["Engine repair"],"benefits":_benefits(),"warranty":WARRANTY_SPARE},
    {"slug":"rk-piston-ring","category":"agricultural-spare-parts","name":"Piston & Ring Set — OEM Spare","model":"RK-PISTON","badges":["Spare"],"images":[COVER["piston"]],"specs":{"Type":"Piston & Ring","Grade":"OEM"},"features":_features(["Precision-fit","Long life"]),"applications":["Engine rebuild"],"benefits":_benefits(),"warranty":WARRANTY_SPARE},
    {"slug":"rk-carburetor","category":"brush-cutter-spare-parts","name":"Carburetor — Brush Cutter / Chain Saw","model":"RK-CARB","badges":["Spare"],"images":[COVER["carburetor"]],"specs":{"Type":"Carburetor","Compatibility":"Brush Cutters & Chain Saws"},"features":_features(["Direct fit replacement"]),"applications":["Service & repair"],"benefits":_benefits(),"warranty":WARRANTY_SPARE},
    {"slug":"rk-recoil-starter","category":"power-weeder-spare-parts","name":"Recoil Starter Assembly","model":"RK-RECOIL","badges":["Spare"],"images":[COVER["recoil"]],"specs":{"Type":"Recoil Starter Assembly"},"features":_features(["Easy-pull mechanism","Tested for durability"]),"applications":["Weeder repair","Engine repair"],"benefits":_benefits(),"warranty":WARRANTY_SPARE},
]
